export enum CategoriesEnum {
  CLOTHING = 'clothing',
  SUBSCRIPTIONS = 'subscriptions',
  INSURANCE = 'insurance',
  BILLS = 'bills',
  HOME_EXPENSES = 'home_expenses',
  HOUSEHOLD_ITEMS = 'household_items',
  EDUCATION_CULTURE = 'education_culture',
  ELECTRONICS = 'electronics',
  MISCELLANEOUS_INCOME = 'miscellaneous_income',
  FINANCING = 'financing',
  HOBBIES_LEISURE = 'hobbies_leisure',
  ENTERTAINMENT = 'entertainment',
  INVESTMENTS = 'investments',
  WEDDING = 'wedding',
  GIFTS = 'gifts',
  REFUELING = 'refueling',
  RESTAURANTS_BARS = 'restaurants_bars',
  HEALTH_PERSONAL_CARE = 'health_personal_care',
  SHOPPING = 'shopping',
  CAR_EXPENSES = 'car_expenses',
  BANKING_FEES = 'banking_fees',
  MISCELLANEOUS_EXPENSES = 'miscellaneous_expenses',
  SPORTS = 'sports',
  SALARY = 'salary',
  TELEPASS = 'telepass',
  PUBLIC_TRANSPORT = 'public_transport',
  MISCELLANEOUS = 'miscellaneous',
  TRAVEL = 'travel',
}

export const categoriesLabels: Record<CategoriesEnum, string> = {
  [CategoriesEnum.CLOTHING]: 'Abbigliamento',
  [CategoriesEnum.SUBSCRIPTIONS]: 'Abbonamenti',
  [CategoriesEnum.INSURANCE]: 'Assicurazioni',
  [CategoriesEnum.BILLS]: 'Bollette',
  [CategoriesEnum.HOME_EXPENSES]: 'Casa e spese',
  [CategoriesEnum.HOUSEHOLD_ITEMS]: 'Cose per la casa',
  [CategoriesEnum.EDUCATION_CULTURE]: 'Educazione e cultura',
  [CategoriesEnum.ELECTRONICS]: 'Elettronica',
  [CategoriesEnum.MISCELLANEOUS_INCOME]: 'Entrate varie',
  [CategoriesEnum.FINANCING]: 'Finanziamenti',
  [CategoriesEnum.HOBBIES_LEISURE]: 'Hobby e Tempo libero',
  [CategoriesEnum.ENTERTAINMENT]: 'Intrattenimento',
  [CategoriesEnum.INVESTMENTS]: 'Investimenti',
  [CategoriesEnum.WEDDING]: 'Matrimonio',
  [CategoriesEnum.GIFTS]: 'Regali',
  [CategoriesEnum.REFUELING]: 'Rifornimenti',
  [CategoriesEnum.RESTAURANTS_BARS]: 'Ristoranti e bar',
  [CategoriesEnum.HEALTH_PERSONAL_CARE]: 'Salute e cura personale',
  [CategoriesEnum.SHOPPING]: 'Spesa',
  [CategoriesEnum.CAR_EXPENSES]: 'Spese auto',
  [CategoriesEnum.BANKING_FEES]: 'Spese bancarie',
  [CategoriesEnum.MISCELLANEOUS_EXPENSES]: 'Spese varie',
  [CategoriesEnum.SPORTS]: 'Sport',
  [CategoriesEnum.SALARY]: 'Stipendio',
  [CategoriesEnum.TELEPASS]: 'Telepass',
  [CategoriesEnum.PUBLIC_TRANSPORT]: 'Trasporti pubblici',
  [CategoriesEnum.MISCELLANEOUS]: 'Varie',
  [CategoriesEnum.TRAVEL]: 'Viaggi',
}
